### ISSUE TITLE
Incompatibilities with Slop Crew

### ISSUE THREAD

**Issue by NotNite** [viliger2/BRC_CharacterAPI#1]
Heya,

I'm the developer of [Slop Crew](https://github.com/NotNite/SlopCrew), the BRC multiplayer mod. Your mod crashes people when they connect to Slop Crew using it, so I have to disconnect every player using your mod. I incorrectly attributed this to an intentional attack, but after some code review, it's most likely caused by your plugin.

Slop Crew syncs the current character by casting the `character` field on the `Reptile.Player` to an int, then casting it back and constructing a player. Your plugin sets this field to a value not in the enum, which crashes the game when constructing a player without the plugin installed.

The solution I have is [disconnect the connection when an invalid value is encountered](https://github.com/NotNite/SlopCrew/blob/fa69b66b2a0a776d6ca2bbac1163ea8949ca0f29/SlopCrew.Server/ConnectionState.cs#L77-L83). I also log the connection's IP, which I was using to determine if it was an attack or not (and I'll probably remove it later).

If you expose an API ([similar to how Slop Crew does it](https://github.com/NotNite/SlopCrew/blob/main/INSTALL.md#using-the-api)), I'd be happy to implement it into Slop Crew to not have to disconnect people with your plugin (e.g. broadcasting a character enum that can be used in place of your custom enum). Alternatively, consider reworking your plugin to not use a custom enum.

Thanks!

**Comment by TheSmallBlue** [comment]
While this is being discussed, it may be smart to set slopcrew as incompatible in code (or CharacterAPI as incompatible in Slopcrew). From the [bepinex documentation](https://docs.bepinex.dev/articles/dev_guide/plugin_tutorial/2_plugin_start.html):

![image](https://github.com/viliger2/BRC_CharacterAPI/assets/24967815/b49ca40a-fb72-4f0b-9d5a-10c5af697747)

**Comment by viliger2** [comment]
@TheSmallBlue this is a good suggestion and I will most likely implement it for now, since from the very start I was sure that it will not work with multiplayer mod, I was expecting crashes from other clients, but hoping it wouldn't happen.

@NotNite in general, I agree with you that using custom values for Characters enum is a bad practice, but so much of the game relies on that I would have to rewrite practically half of the code related to characters in order to make it so that you don't need to use custom enum values, which I am not willing to do. I am just not sure what is preventing you from just validating enum and if it is out of range, then assign a random valid one, assuming of course server doesn't control player's character and it is still client-side.

**Comment by NotNite** [comment]
There's been a PR to use the modulo operator, but I haven't had time to update the server just yet: https://github.com/SlopCrew/SlopCrew/pull/35

**Comment by viliger2** [comment]
As long as the host has authority on what skin to chose it shouldn't be an issue.

We can maybe also instead of validating on server can try validating on clients, that would allow people with mods see other modded characters, let's say via, as you said, API that I would expose. That would require a slight rewrite, so characters get their enums on initialisation instead of receiving them only when player changes character.  

But since currently we just assign enums one after another, load order is what will determine what skins people would see. And I don't think this is something that can be fixed outside of closely integrating mods and writing comparability layers, like in addition to enum sending character's name. Game's characters just use their enum names as names when needed, while I use whatever user set as a name for a character. Is it worth it? Probably not, but just a thought.

**Comment by viliger2** [comment]
SlopCrew is now setting all modded characters as Red to players without a mod, so the issue, while not fully resolved, can be closed.
